server:
  port: 9092
spring:
  mail:
    protocol: smtp
    host: smtp.sina.cn
    username: verygoodwlk@sina.cn
    password: ken123456

dubbo:
  application:
    name: mail_service
  registry:
    address: zookeeper://192.168.159.188:2181
  protocol:
    port: -1
  consumer:
    check: false