server:
  port: 8080
spring:
  thymeleaf:
    cache: false
dubbo:
  application:
    name: user_web
  registry:
    address: zookeeper://192.168.159.188:2181
  consumer:
    check: false
    timeout: 20000
    retries: 0
