server:
  port: 9091
spring:
  datasource:
    url: jdbc:mysql:///sz_1903?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://192.168.159.188:2181
  protocol:
    port: -1
  consumer:
    check: false
mybatis-plus:
  mapper-locations:  classpath:com/qf/dao/mapper/*.xml
  type-aliases-package: com.qf.entity